name: Build & Deploy Website

on:
  push:
    branches:
      - dev
      - master

jobs:
  release:
    name: Build & Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"

      - name: Copy .env.example
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          else
            echo ".env file already exists. Skipping the copy step."
          fi

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: homepage
          path: dist

      - name: Upload homepage.zip to Server
        if: success() && steps.build.outputs['dist'] != ''
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "${{ secrets.SERVER_IP }}"
          username: ${{ secrets.SERVER_USER }}
          key_path: ./private_key.pem
          source: "homepage.zip"
          target: "/home/admin/"

      - name: Deploy Website on Server
        if: success() && steps.build.outputs['dist'] != ''
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "${{ secrets.SERVER_IP }}"
          username: ${{ secrets.SERVER_USER }}
          key_path: ./private_key.pem
          script: |
            cd /home/admin
            if [ -f "homepage.zip" ]; then
              echo "Found homepage.zip, deploying..."
              rm -rf homepage
              mkdir homepage
              unzip homepage.zip -d homepage
              rm homepage.zip
              echo "Deployment successful!"
              sudo systemctl restart nginx
            else
              echo "Error: homepage.zip not found!"
              exit 1